### ISSUE TITLE
API v2 Documentation does not work

### ISSUE THREAD

**Issue by DIDoS** [OSSIndex/website#16]
The page https://ossindex.net/docs/restapi2 returns a 404.

It is linked on several documents and the index page of ossindex.net

**Comment by OSSIndex-Admin** [comment]
Thanks for the pointer. Working on that now...

**Comment by OSSIndex-Admin** [comment]
On moving to a new server, I neglected to disable some default configured paths resulting in the masking of OSS Index pages. This should be fixed.
