### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by NancyChunlan** [OSSIndex/website#17]
Previously it works fine to scan the vulnerabilities.  From few days ago, we met an issue as below:
[INFO] OSS Index dependency audit
java.net.ConnectException: Server Error (500)
	at net.ossindex.common.request.AbstractOssIndexRequest.performPostRequest(AbstractOssIndexRequest.java:66)
	at net.ossindex.common.request.PackageRequest.run(PackageRequest.java:72)
	at net.ossindex.maven.utils.DependencyAuditor.run(DependencyAuditor.java:109)
	at net.ossindex.maven.plugin.OssIndexMojo.execute(OssIndexMojo.java:189)

After checked the code, seems https://ossindex.net/v2.0/ can not be found now.
Would you please help to check this?
Thanks!

**Comment by OSSIndex-Admin** [comment]
Curious. I am having rather severe internet problems at the office at the moment, so a full test is difficult at the moment. I am pulling data down from the API fine. Do you get a result from here:
```
https://ossindex.net/v2.0/package/maven/bcprov-jdk16
```

Would you be able to send me the pom file you are testing from? The issue might be a server error related to a specific dependency (an exception on one of them in particular).

Once my internet connection is repaired I will try some more serious tests.

**Comment by OSSIndex-Admin** [comment]
My internet is back up, and I am definitely seeing the same issues you are. We have been moving the servers 1600 KM to a new office, so Jenkins has not been doing his job of informing me when things break.  I will resolve the problem post-haste and then get Jenkins back up and running.

**Comment by OSSIndex-Admin** [comment]
Null pointer exception on server:
```
Aug 04 15:03:35 heimdallr run.sh[32154]: java.lang.NullPointerException
Aug 04 15:03:35 heimdallr run.sh[32154]:         at com.vor.resource.VorResource.compareTo(VorResource.java:103)
Aug 04 15:03:35 heimdallr run.sh[32154]:         at com.vor.resource.VorResource.compareTo(VorResource.java:19)
```

**Comment by OSSIndex-Admin** [comment]
The issue has now been resolved. Thank you very much for the notification, and sorry for the downtime.

**Comment by OSSIndex-Admin** [comment]
(This was a server side fix -- the client does not require upgrading)
