### ISSUE TITLE
Search for scoped NPM packages

### ISSUE THREAD

**Issue by tomraithel** [OSSIndex/website#20]
### Current behaviour:
If I search for a npm package with a scope in its name (e.g. `@babel/code-frame`), I get no results. For some packages it works by using the npm URL (in this case `babel-code-frame` works) but for other packages like `@types/node` there is no way to retrieve information about the package. Neither via the website search, nor via the API.

### Expected behaviour
A search for `@types/node` should find this package: https://www.npmjs.com/package/@types/node

### Steps to reproduce
API Request:
```
POST https://ossindex.net/v2.0/package

[
  {"pm": "npm", "name" : "@types/node"}
]
```

API Response (id: 0 indicates nothing is found):
```
HTTP/1.1 200 OK
Date: Mon, 20 Nov 2017 08:28:05 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Server: Jetty(9.3.z-SNAPSHOT)

[
  {
    "id": 0,
    "pm": "npm",
    "name": "@types/node",
    "vulnerability-total": 0,
    "vulnerability-matches": 0
  }
]
```

**Comment by OSSIndex-Admin** [comment]
Thanks for the information. I will see what I can do. I have a few issues that have been raised that are on my plate at the moment. I am hoping to be able to get to several of them shortly (some are in progress, but will take a bit more effort).

**Comment by ken-duck** [comment]
Oof. I lost track of some issues apparently. I know that the API does not support scope yet. We are currently working on an API that will replace the current OSS Index API. I will add an issue to our internal tracking to ensure scopes can be handled.

**Comment by tomraithel** [comment]
Is this issue resolve by now?

**Comment by ken-duck** [comment]
Heh. Yes, long since resolved. My fault for not closing it. The new API has been available for a while. The trick is in how to create the coordinate "PURL". The main thing is to not include the `@`.

A PURL is defined as follows:

```
pkg:<format>/<namespace>/<name>@<version>
```

Here is an example:
```
pkg:npm/impala/bmap@1.0.3
```

The OSS Index URL for the package: https://ossindex.sonatype.org/component/pkg:npm/impala/bmap@1.0.3

A `curl` command to get the JSON data:

```
curl -X POST "https://ossindex.sonatype.org/api/v3/component-report" -H "accept: application/vnd.ossindex.component-report.v1+json" -H "Content-Type: application/vnd.ossindex.component-report-request.v1+json" -d "{ \"coordinates\": [ \"pkg:npm/impala/bmap@1.0.3\" ]}"
```
