### ISSUE TITLE
Mismatch on Affected Version for vulnerability id:  8397099396 - crypto-js

### ISSUE THREAD

**Issue by sec9** [OSSIndex/website#21]
Affected versions are  not : "<3.2.1-4"    but  "< 3.1.2-4"
This make auditjs to render a false positif  everytime crypto-js  is detected as today,  latest version of crypto-js is "3.1.9"
----
RandomBytes is not random enough
https://github.com/evanvosberg/crypto-js/blob/59e465a8055946e84099bfaa8d9ce0e1d1371f51/src/core.js#L274-L281

This is not generating sufficiently random bytes. Math.random was never intended for use in cryptographic applications.

see:
https://code.google.com/p/chromium/issues/detail?id=246054

ID: 8397099396
**Affected versions: <3.2.1-4**
References:
  * https://github.com/brix/crypto-js/issues/7

**Comment by OSSIndex-Admin** [comment]
Absolutely right. Thanks for the heads up! Fixed.
