### ISSUE TITLE
invalid range for  [maven] commons-fileupload/commons-fileupload

### ISSUE THREAD

**Issue by sebastiankirsch** [OSSIndex/website#22]
https://ossindex.net/resource/cve/8400711307 states in the text

> Apache Commons FileUpload before 1.3.3

but the affected resources list

> apache:commons_fileupload <0

It is thus also incorrectly listed here: https://ossindex.net/resource/package/7015420058/vulnerabilities

**Comment by OSSIndex-Admin** [comment]
Thank you for the report. This is quite strange. I will fix the issue by hand for this particular case later on today, but will dig further to see how we managed to load an incorrect version range.

**Comment by OSSIndex-Admin** [comment]
It appears that sometime in the past there was a human error that affected the loading of this CVE. I have not identified any other vulnerability with the same error (and have resolved this one).

I am currently in the process or rewriting the code that imports vulnerabilities from the National Vulnerability Database (where this vulnerability was sourced), and will at the same time write some code to validate that the published data is reasonable and correct.

Thanks for the help!
