### ISSUE TITLE
VSTS/TFS Build Extension for OSSINdex

### ISSUE THREAD

**Issue by marc-mueller** [OSSIndex/website#25]
Hi 

I'd like to implement a build task for VSTS/TFS which will perform a vulnerability check for the projects dependencies (currently NuGet and npm). Your API looks very promising to achieve our goal. Therefore I have a few questions:

- Is it legal to use your service in our task extension? Are there any restrictions? The extension will be available for free in marketplace.visualstudio.com.
- How do we handle the dependencies? Are there already implementations which can be executed by command line to get all the packages with its dependencies?

Thanks for your feedback!
Marc

**Comment by ken-duck** [comment]
Hi! The notification from GitHub fell through the cracks of my email; sorry for not responding sooner.

I will double check, but I the use of the API in your extension seems perfectly reasonable to me. I am assuming that when someone uses the extension, it is the user's copy of your extension that will be accessing the API. Is this correct?

We do not currently have a stand-alone library in C#/.NET that will extract dependencies. You can check out the source for [DevAudit](https://github.com/OSSIndex/DevAudit) which does some of that internally and might provide what you need. Our npm audit tool (audit.js) uses npm directly to get what it needs (and is written in JavaScript) so it likely will not be much help.

In particular, you will find the "PackageSources" directory to contain much of what you need for dependencies: https://github.com/OSSIndex/DevAudit/tree/master/DevAudit.AuditLibrary/PackageSources

A quick glance at that code seems to indicate that the "Yarn" source (which handles npm packages) can find direct dependencies, but I suspect it does not get recursive dependencies. Those would technically be stored in the `node_modules` folder for an installed project, so a recursive search for package.json files would probably give you what you need. I believe that is what the `npm` operations in node.js do as well.

I hope this helps!

**Comment by ken-duck** [comment]
Ooh! A quick side note. In a couple of months we will be releasing a new version of the "package:version" API and other APIs will be deprecated. It will operate rather similarly to the [existing API](https://ossindex.sonatype.org/api/package-version-search) but there will be differences.

Incidentally, this API will also give access to a larger and increasing number of vulnerabilities.

**Comment by marc-mueller** [comment]
Hi @ken-duck 

Thanks for your answer. The build extension will be installed on VSTS/TFS and then be run on the build agent itself (on the build agent of the user). Technically, the build agent will calculate all the dependencies and sends this request to your API. The results will then cause warnings/errors and/or a short report. At the end, there will be many different users accessing your API from their build system (open source and commercial software products will be using it). 

The extension will be implemented in TypeScript since we need cross platform execution. I'll check your links and try to identify how we can calculate the dependencies the best way.

Is there any preview of the new API?

Thanks
Marc

**Comment by ken-duck** [comment]
We would be quite pleased if you were to use our service with your extension. I am quite interested to see it when you have it working.

The API is still in the design phase, though it looks quite possible that the development of the API will be moved up. I will let you know as soon as I have more information or a preview available.

**Comment by roly445** [comment]
Sorry to add this to the ticket rather tan create a new one, but I'm in the process of creating a plugin for the cakebuild utility and it will do a similar thing to what the VSTS/TFS build extension will do.  Can I assume that this is also OK?

**Comment by ken-duck** [comment]
Awesome. That would be great! The only thing that would be "of concern" is if the data is being sold. So long as your plugin is free there should not be a problem.

Do keep me up to date on progress. I would definitely like to be aware of anything out there, and it will also allow me to inform you of any API changes (particularly as we are working on the new API (coming soon).

**Comment by marc-mueller** [comment]
Just a short update:  A first alpha version is running on our test systems and looks promising.

If we go to the public marketplace: Is there any text we could add to the description that this extension is using your service? Do you have a sample text? Do you have any requirements on how we state that we are using your service in the build extension?

Thanks for your feedback!
Marc

**Comment by OSSIndex-Admin** [comment]
Hi.

Just letting you know I saw your email. I will check with management to see if they have any preference.

Its good to hear things are moving along!

FYI, in another few weeks we will be releasing the next iteration of the API. It is quite similar to the existing “package” API, so hopefully it will not require to much effort to migrate.

Ken

**Comment by OSSIndex-Admin** [comment]
I checked with marketing. The suggested something along the lines of "powered by data provided by Sonatype OSSIndex" with a hyperlink to the OSSIndex site, if that makes sense to you.

Thanks!

Please do let me know when you put it up. I am quite interested in seeing it.

Ken

**Comment by dealproc** [comment]
@roly445 - Did you get anywhere with the CakeBuild plugin, and if so, is it available for others to use?  Have a requirement to be able to check for security vulnerabilities, and OSSIndex seems to be the ticket, and would like to use it in conjunction with CakeBuild if possible.

**Comment by ken-duck** [comment]
Whoops, sorry for the delay. I missed seeing this come in. Working on a reply now.

**Comment by ken-duck** [comment]
Alright, here are the current settings:

* In all cases, the maximum number of components per request is 128
* Anonymous users have a "bucket" with 16 requests which replenish at a speed of one request per minute
* Authenticated users have a "bucket" with 64 requests which replenish at a speed of one request per minute

If you have more than 128 components to check, then multiple requests should be performed. The restriction also ensures that the server can respond in a reasonable amount of time, even while under load.

I would also advise that you build in some sort of caching if possible. Vulnerabilities are updated on a daily basis, so if the same build is performed multiple times, or if multiple builds request the same package, then a cache can wildly reduce the number of required requests.

You mechanism for handling credentials sounds good. Bear in mind that both the user email and the API token are required for authenticating.

I hope this answers the questions to your satisfaction?

**Comment by marc-mueller** [comment]
Hi Ken

Thanks a lot for your feedback. So we will loop through the buckets of 128 components and provide the user the ability to work in authenticated mode by providing credentials for this build task.

Caching is actually the only way to get that up and running since otherwise the builds would hit the limits during the first working hour a day. My only concern about caching was that we might somehow be violating the license agreement by storing the results in our cache. If this is allowed from your side, we will implement a cache and get this task up and running.

Thanks,
Marc

**Comment by ken-duck** [comment]
Quick update. I did not miss your message. I am confident that caching for this purpose is perfectly fine, but have reached out to appropriate internal sources to get the official word. I will write you back as soon as I hear (alas, the person I am trying to contact is travelling rather a lot this week).
