### ISSUE TITLE
npm issues not available with ProGet API

### ISSUE THREAD

**Issue by ken-duck** [OSSIndex/website#26]
It seems the npm issues are not available with the ProGet API.

**Comment by BenLubar** [comment]
It might not be that - the customer said they had a firewall whitelist entry for ossindex.net, but the version of the plugin they were using accessed the API through vorsecurity.com.

**Comment by ken-duck** [comment]
Understood. If there continues to be a problem please contact me directly and I can debug the issue.

**Comment by ken-duck** [comment]
Closing. The ProGet plugin and OSS Index have both changed dramatically in the intervening time. I expect the problem has been resolved.
