### ISSUE TITLE
Invalid slf4j-api report

### ISSUE THREAD

**Issue by rmannibucau** [OSSIndex/website#28]
Hi,

https://ossindex.sonatype.org/component/pkg:maven/org.slf4j/slf4j-api@1.7.26 reports slf4j-api 1.7.26 as being affected by a CVE whereas it was released to fix it. 1.7.25 and 1.8.0 alphas were affected. I guess it is an issue in comparing versions.

Any hope it gets fixed?

Romain

**Comment by ken-duck** [comment]
Yup. It was in fact fixed last night, and I am expecting to see the data finish finding its way through our processing pipeline sometime today. If I do not then I will manually take over and make sure it gets pushed through.

Thank you for the report!

**Comment by ken-duck** [comment]
I just verified that the updates are complete.

Thanks for the help!
