### ISSUE TITLE
Vulnerability reported for wrong package

### ISSUE THREAD

**Issue by dan-brewster** [OSSIndex/website#3]
Hello,

We've been experimenting with using the npm vulnerability API so far, and it has been great in finding issues with the packages we have installed. The database is by far the most extensive we've seen.

However, we have encountered an issue with one of our packages. Namely, the `sntp` package seems to be picking up the vulnerabilities from the same version of the `hapi` package. I believe this is because they share the same `scm_id`, though I'm not completely sure. See below for requests and responses that show this:

```
curl https://ossindex.net/v1.1/search/artifact/npm/sntp/2.0.1

[
  {
    "id": 7014463224,
    "name": "sntp",
    "version": "",
    "description": "SNTP Client",
    "package_manager": "npm",
    "package": "https://ossindex.net/v1.1/package/7014463224",
    "package_id": 7014463224,
    "hasVulnerability": false,
    "vulnerabilities": "https://ossindex.net/v1.1/package/7014463224/vulnerabilities",
    "scm": "https://ossindex.net/v1.1/scm/294418698",
    "scm_id": 294418698,
    "project": "https://ossindex.net/v1.1/project/8396639732",
    "project_id": 8396639732,
    "url": "https://www.npmjs.com/package/sntp",
    "search": [
      "npm",
      "sntp",
      "null",
      "2.0.1"
    ]
  }
```

```
curl https://ossindex.net/v1.1/search/artifact/npm/hapi/2.0.1

[
  {
    "id": 7013826322,
    "name": "hapi",
    "version": "",
    "description": "HTTP Server framework",
    "package_manager": "npm",
    "package": "https://ossindex.net/v1.1/package/7013826322",
    "package_id": 7013826322,
    "hasVulnerability": true,
    "vulnerabilities": "https://ossindex.net/v1.1/package/7013826322/vulnerabilities",
    "scm": "https://ossindex.net/v1.1/scm/294418698",
    "scm_id": 294418698,
    "project": "https://ossindex.net/v1.1/project/8396639732",
    "project_id": 8396639732,
    "url": "https://www.npmjs.com/package/hapi",
    "search": [
      "npm",
      "hapi",
      "null",
      "2.0.1"
    ]
  }
```

Here is the error we see when running `auditjs`:

```
...
------------------------------------------------------------
[898/934] sntp 2.0.1 []  [VULNERABLE]
2 known vulnerabilities, 1 affecting installed version

rosetta-flash vulnerability
someone created a alphanum only swf converter, which means that they can in theory use it as a callback at a JSONP endpoint, and as a result, send data across domains.

Prepending callbacks with an empty inline comment breaks the flash...

Affected versions: < 6.1.0
------------------------------------------------------------
...
```

It seems like this is in error? Or are we doing something incorrect? We're not using `hapi` for any dependency in our project, which I've confirmed by checking both the shrinkwrap file and `npm list hapi`.

**Comment by OSSIndex** [comment]
Good grief. I am sorry for this lingering for so long. It seems that it fell off my radar briefly, then I subsequently forgot to check back with the GitHub issues for a long time.

Please accept my profound apologies. I am exploring the issue now.

**Comment by OSSIndex** [comment]
You are quite correct that this is an error. It is caused by some versions of npm packages referring to the incorrect sources. We have found such situations in the past and have been resolving them as they are discovered.

Apologies again for dropping the ball on this issue. We will be much more responsive in the future.

**Comment by OSSIndex** [comment]
Also, FYI: There is a new, much simpler, [v2 API](https://ossindex.net/docs/restapi2) that is available that we are moving all of the tools to. It does not expose quite as much information as the 1.x API at this time, but should have most of the interesting information.

**Comment by OSSIndex** [comment]
Though the sntp vulnerabilities are no longer reported on the package web page, we are still reporting them through auditjs. This is due to the v2.0 API not correctly filtering invalid package links.

**Comment by OSSIndex** [comment]
Bah, even worse (in a sense). The database replication had failed, meaning the secondary database (feeding the API) was out of sync. The master database (feeding the website) was perfectly happy. The secondary has been taken offline pending a full re-sync later on tonight.

A new issue report (#10) has been raised to track creation of a periodic check to ensure we do not fall out of sync again.

The failure likely happened last week sometime when we upgraded the database machine's disk space and memory, and started syncing a couple of additional tables.

We will continue to monitor sntp on our CI server to ensure there are no regressions.

**Comment by dan-brewster** [comment]
@OSSIndex Great, thank you. I saw it was reporting incorrect vulnerabilities when I checked after your initial response, but those have now been cleared up. Thanks for responding and for the great tool!

**Comment by OSSIndex** [comment]
Resolving your issue found a couple of underlying problems; it was quite useful.

Thanks very much for the feedback. We are ramping up our efforts both on our various clients as well as on the server and data side, and it definitely helps to know that people are finding it useful.
