### ISSUE TITLE
Automatically monitor unbounded vulnerabilities for solutions

### ISSUE THREAD

**Issue by OSSIndex-Admin** [OSSIndex/website#5]
There are some situations where there are vulnerabilities with unbounded ranges, for example version ranges like:

* >0
* undefined

We should automatically scan particular links to identify either where there is a mistake, or where there is a change in the data. Some particularly interesting links to check include:

* GitHub issue pages, to see if they are closed
* Node Security Project pages
* Snyk pages

Even if we do not update automatically, we should send a notification email to an analyst in any case.

**Comment by ken-duck** [comment]
Moved to JIRA for internal tracking
