### ISSUE TITLE
Reports should include sources and "No known problem"(or some such) in results

### ISSUE THREAD

**Issue by jlongo62** [OSSIndex/website#7]
Consider the page: [https://ossindex.net/resource/package/7098956883?pm=nuget](url). A user does not know if this entity has been scanned or not - or if it is just in a list of software to be scanned. In my opinion, the results should include the source of info and "No known problems". If the source cannot be determined to have scanned the item, then it should not be included in the list.  

This is similar to EHR's handling of Allergies which display NKA if the information is known, that there are "no known allergies" vs no one has ever asked, in which case the results are empty.

**Comment by OSSIndex** [comment]
Thanks for the feedback. I understand and agree with the need, but will have to spend a bit of time thinking about the best way to implement the feature.

Concerning the source link: on the "package" page we provide any links to sources provided in the nuget data. If none is provided all is not lost, if a "project" link exists on the right you can click on that. The "project" is a higher order construct which might contain a link to sources provided from elsewhere (either manually added or through automated means).

I agree that this is cumbersome and will look into the best way to provide the "project" source link on the package page itself -- perhaps flagging these links in such a way as it is understood that they are not necessarily officially provided nuget sources.

**Comment by jlongo62** [comment]
thank you for seriously considering this request. I think I may have mis-communicated. Consider:
https://ossindex.net/resource/package/8399170945?pm=nuget  It shows a number of vulnerabilities, but not the source identifying the vulnerability - ie ' snyk.io'.  Then look at https://ossindex.net/resource/scm/301023616. The vulnerabilities are blank. Does that mean it has none ? Or does it mean it has not been scanned ? And what scan resources have been used ?

If the answer is "Un-scanned", then the report should indicate "un-scanned". If the item is scanned, but no vulnerabilities have been found, then the report should indicate the "Scan Service", and "no known vulnerability"

This is important, because the security folks I might present this data to as justification will ask these questions -- and I cannot answer them. If this information is provided, it is the hammer we need to beat them into submission.

**Comment by OSSIndex** [comment]
I understand, though your added explanation definitely helps define the feature better. I would like to describe our processes here a bit more so we can see how best to provide you the information you need and build you a better hammer.

What we do
-------------

We report on vulnerabilities that have been published in any one of a variety of places, and in a number of ways. To be clear: we do not currently scan source looking for new vulnerabilities, though that feature is on its way. More on that later.

The reference links you see on a vulnerability page show the "evidence" for the vulnerability. This includes other vulnerability database entries (NVD/mitre, snyk, node security project, etc.) It also includes issue report, pull requests, and commit references, as well as applicable blog postings and advisories. All of this is "evidence" that backs up the vulnerabilities.

Some vulnerabilities are brought to our attention through some of the aforementioned vulnerability databases such as the NVD, snyk, and nsp, while others we have identified by scanning through github issues or through manual searches. We are continually developing new mechanisms to find vulnerabilities.

How we can improve the references
--------------------------------------
We could try to highlight the "primary" source which brought the vulnerability to our attention first. Sometimes this is snyk/nsp, but sometimes we found it elsewhere *before* they published and we added their links in later.

We could try to highlight the more interesting sources (mitre, snyk, nsp, etc).

We would generally consider the NVD to be a "primary source". Should the same vulnerability be reported in both NVD and elsewhere, it is the NVD reference that we keep. Note that we do edit our NVD entries to improve them, however. There are cases where the affected version list is insufficient, for example. This is an activity we have only recently undertaken.

Reporting on the package "scanning" status
-------------------------------------------------
This is certainly one of the more interesting problems. We can immediately report on a few different statuses:

* Obviously if there *is* a (non-flagged) vulnerability then there is a vulnerability
* If there are no known vulnerabilities, but we have identified that there is no CPE code entry for the project in the National Vulnerability Database then there is *some* level of checking performed. Perhaps we could say these have "no known vulnerability", but it isn't as certain as those in the next group:
* If we have identified a github repository for a project then we have some automated scanners running looking for vulnerabilities which are fed into a queue for analysis by an auditor. This queue is long, but we are chewing through it at a reasonable rate. Therefore we could consider any package in this situation as having "no known vulnerability".
* There might be "un approved" vulnerabilities associated with a package (these are the vulnerabilities with a red flag). These show you projects that we have definitely been "scanning" but have not necessarily found a real vulnerability. This package could be considered "under investigation"
* Some vulnerabilities might be "approved" but are marked as being "Unconfirmed" or "Under investigation". In these cases we feel there is enough evidence that one might want to be concerned, but the evidence has not reached a level that we are confident in saying it is absolutely a vulnerability.

Vulnerability scanning
------------------------
Currently we report on vulnerabilities that have been discovered and published somewhere. We are working on adding automated scanning to packages, starting with NuGet packages and then moving to other languages/packages. This automated scanning would be done using open source/free static analysis tools, plus some tools of our own that are in development. Anything found by these scanners would have to be approved by an analyst before being considered a vulnerability. We would, of course, report any findings to the appropriate code owners.

Improving your hammer
---------------------------
We have a long queue of packages and vulnerabilities we are continually running through, as well as new vulnerability sources to consider. If you wanted to send a list of packages you are interested in I can try to move them closer to the top of the stack. In general we try and prioritize by the packages that people are actually using, and this list would be proof they are packages people are actually using ;)

**Comment by OSSIndex** [comment]
In the next week or so we will be publishing some new code which adds a label in the "Vulnerabilities" section on various pages to indicate projects that are likely being scanned. The scanning situation is determined through a series of checks (simplified descriptions below):

* Existing vulnerability: vulnerabilities are listed
* Project/Package in local scanning queue: "No known vulnerabilities"
*  Project/Package has an assigned CPE: says "No known vulnerabilities"
* Otherwise: "Project not in scanning queue"

This does not necessarily provide 100% knowledge on what is being scanned, because our data comes not only from our package scans and data from the National Vulnerability Database, but we also pull data from a variety of other databases and resources. These databases do not release information on what packages they scan, so there are quite possibly packages being scanned for vulnerabilities that are not identified as being scanned in our data.

We also perform a reasonable amount of manual scanning which also does not show in the data.

**Comment by OSSIndex** [comment]
It is also worth noting that as we are adding various scan types, various packages/projects might not be scanned by the full set of scanners, it depends on the support available for the language, package manager, and source repository type.

**Comment by OSSIndex** [comment]
If you visit the vulnerability page for a project/package that displays the references you will see different colours given to various references.

* Blue: Primary reference -- this is the reference from which we were first notified of the vulnerability
* Green: "Evidence" -- these are references that were used to provide some of the attributes, such as version overrides, or additional interesting information. These are often links providing corroboration for the vulnerability.
Red: "Dead link" -- not yet used, but will be used to indicate dead links.

**Comment by ken-duck** [comment]
Closing due to the website and API being completely rewritten quite some time ago, and I forgot this repo and issues existed for a long time O.o
